config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home', as: 'home'
  get 'about_us', to: 'pages#about', as: 'about'
  get 'lizards/:number', to: 'pages#lizards', as: 'lizards'

  get 'doctor_whos', to: 'doctor_whos#index', as: 'doctor_whos'
  get 'doctor_whos/:number', to: 'doctor_whos#show', as: 'doctor_who', id: /\d+/
  # get 'pages/home'
  # get 'pages/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor_who.rb
class DoctorWho < ApplicationRecord
  validates :character, :quote, presence: true
  validates :character, numericality: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/doctor_whos_controller.rb
class DoctorWhosController < ApplicationController
  def index
    @doctor_whos = DoctorWho.all
  end

  def show
    @doctor_who = DoctorWho.where(id: params[:number]).first
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def lizards
    @lizards = params[:number].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctor_whos_helper.rb
module DoctorWhosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/doctor_whos/_doctor.html.erb
<% if isCollection then%>
    <ul>
      <% @doctor_whos.each do |doctor_who| %>
          <li><h5>Character: <%= doctor_who.character %> | Quote: <%= doctor_who.quote %></h5></li>
      <% end %>
    </ul>
<% else %>
    <h5>Character: <%= @doctor_who.character %> | Quote: <%= @doctor_who.quote %></h5>
<% end %>

app/views/doctor_whos/index.html.erb

<%= render partial: 'doctor', collection: @doctor_whos, locals: {isCollection: true} %>

app/views/doctor_whos/show.html.erb
<%= render partial: 'doctor', object: @doctor_who, locals: {isCollection: false} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KyleIsSick</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <%= render partial: 'partials/nav' %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!--Samuel L. Ipsum http://slipsum.com/-->
<h2>Hold on to your butts</h2>

app/views/pages/home.html.erb
<!--Samuel L. Ipsum http://slipsum.com/-->
<h2>Uuummmm, this is a tasty burger!</h2>
<ul>
  <li><%= link_to "12 Lizards", lizards_path(12) %></li>
  <li><%= link_to "444 Lizards", lizards_path(444) %></li>
  <li><%= link_to "9672 Lizards", lizards_path(9672) %></li>
</ul>

app/views/pages/lizards.html.erb
<ul>
  <% @lizards.times do %>
    <li>
      🦎
    </li>
  <% end %>
</ul>

app/views/partials/_nav.erb
<nav>
  <ul>
    <li><%= link_to 'home', home_path %></li>
    <li><%= link_to 'about', about_path %></li>
  </ul>
</nav>